---
name: Regression Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  regression:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        # renovate: datasource=github-releases depName=coreruleset/coreruleset versioning=semver
        CRS_VERSION: ['4.28.0']
        python-version: ['3.11', '3.12', '3.13']

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true

      - name: Set up Python 3
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev

      - name: "Run unit tests"
        run: |
          uv run pytest -vs

      - name: "Run crs linter tests for ${{ matrix.CRS_VERSION }}"
        run: |
          curl -sSL  https://github.com/coreruleset/coreruleset/archive/refs/tags/v${{ matrix.CRS_VERSION }}.tar.gz -o - | \
           tar xzvf - \
              --strip-components=1 \
              --wildcards "*/rules/*" "*/tests/*" "*/crs-setup.conf.example" "*/util/*"

          uv run crs-linter \
            --debug \
            -o github \
            -d . \
            -r crs-setup.conf.example \
            -r 'rules/*.conf' \
            -t util/APPROVED_TAGS \
            -f util/FILENAME_EXCLUSIONS \
            -v ${{ matrix.CRS_VERSION }} \
            -T tests/regression/tests/ \
            -E tests/TESTS_EXCLUSIONS
